### ISSUE TITLE
Reduce the size of the Auction on disk (optimize storage)

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#137]
Reduce the size of the bid record, and the auction rewards size on disk. The auction data would be physically stored differently and reported differently.  We will need to retire the current reporting and implement new reporting.
Important for size, scalability and health of mainnet. Presently we are strictly bounded by the number of delegators today. We cannot remove the delegator cap without this change.  The community is experiencing pain at the moment with the limit.  There are things we can do to to help validators out (eject small delegators, set a minimum delegation amount for a given validator)

Reduce the size of the bid record, and the auction rewards size on disk. The auction data would be physically stored differently and reported differently.  We will need to retire the current reporting and implement new reporting.

- [x] - [release-blocker] for each validator bid, write all delegated bids to global state beneath a long compound key of (validator_public_key, delegator_public_key) instead of inserting them directly into a collection stored in the validator bid record itself.
- [x] - [release-blocker] update all affected logic in system auction, ee test support, and the global state updater tool. 
- [x] - [release-blocker] repair bid reporting from the ee and the node to handle the new structure; bids written in the legacy structure and the new structure should both be supported.
- [x] - [release-blocker] migrate prune logic from 1.6 to 2.0, apply it to unbonding scenarios when staked amount drops to 0. (easy, medium)
- [x] - [release-blocker] add one-time upgrade logic to migrate existing Bids to new ValidatorBid + Delegator structure (easy / small)
- [ ] - add a test using the disk_use tool to prove the delta in disk usage running the auction (run the test before and after)
- [ ] - [optimization] cache delegators for validators for previous era to avoid expensive re-lookups. (worth doing)
- [ ] - [optimization] seigniorage recipient snapshot restructure (probably not worth doing)
