### ISSUE TITLE
Contract level events

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#199]
This is a much desired feature in the community.    Host-enforced contract level events.   Needs grooming. 
The objective is to have a way to track the event and the contract that generated the event and on the host side, create an irrefutable record.

The implementation should support the following functionality:
1. What events did a given contract generate - irrefutably
2. Node can ask EE what events a given contract emit? (new endpoint)   

Implementation **notes** (to be updated by the dev once the implementation is complete): 
- [ ] Create a new bounded length event type
- [ ] Update the FFI to take a string (event-generated message) & origin (contract identifier) --> and record it on the host side so there is an irrefutable record of the event.  
- [ ] Create a new endpoint in node to report which events a given contract generated.

**Comment by devendran-m** [comment]
Moved the documentation ticket https://github.com/casper-network/roadmap/issues/205 to the Casper 2.0 Docs Update epic, and closing this epic as all the engineering-related work is complete.
